
import '../scss/style.scss' 
import '../fonts/OpenSans/OpenSans-Bold.ttf'
import '../fonts/OpenSans/OpenSans-BoldItalic.ttf'
import '../fonts/OpenSans/OpenSans-ExtraBold.ttf'
import '../fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf'
import '../fonts/OpenSans/OpenSans-Italic.ttf'
import '../fonts/OpenSans/OpenSans-Light.ttf'
import '../fonts/OpenSans/OpenSans-LightItalic.ttf'
import '../fonts/OpenSans/OpenSans-Medium.ttf'
import '../fonts/OpenSans/OpenSans-MediumItalic.ttf'
import '../fonts/OpenSans/OpenSans-Regular.ttf'
import '../fonts/OpenSans/OpenSans-SemiBold.ttf'
import '../fonts/OpenSans/OpenSans-SemiBoldItalic.ttf'
